### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by pculka** [wevans311082/PoshKPBrute#1]
Hi, on Windows 10 I get the following error:
```
At C:\PoshKPBrute\crack-keepassfile.ps1:96 char:393
+ ...                                                 function try-key($x){
+                                                                         ~
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingEndCurlyBrace
```

The braces seem to be ok on the shown line. Bit badly indented but logically OK ...

**Comment by wevans311082** [comment]
Paul,

Thanks - yeah - loads of people have pointed it out, I even cut an paste errored on the initial blog post - I will get my lazy arse to sort it out soon... Thanks for taking an interest and trying it out.

Wayne

**Comment by hemrickbe** [comment]
delete line 96 in the code and it seems to run
Although I don't get any output when running the script and it seems to complete instantly
also the password file how are the "words" delimited it looks like one block of characters
